# Generated by Django 5.1.2 on 2024-10-22 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('maps', '0003_savedplace_latitude_savedplace_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='savedplace',
            name='label',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
